### ISSUE TITLE
Redux-saga version warning

### ISSUE THREAD

**Issue by marcselman** [colinbate/redux-form-submit-saga#11]
Your package does not seem to be compatible with the latest redux-saga 15.x versions.

**Comment by andredp** [comment]
@colinbate, I've tested and the package is compatible with redux-saga ^0.15.0. The only problem is that you're using a deprecated way of spawning multiple sagas.

Simply changing `yield [...effects]` to `yield all([...effects])` should do the trick.
I can do a PR if you're busy.

**Comment by PeteAndersen** [comment]
I agree, no issues using it w/ latest redux-saga, just depreciation warnings. I've submitted a PR to get it resolved.
