### ISSUE TITLE
Bump redux-form peer dependency to include ^7.0.0

### ISSUE THREAD

**Issue by aaronjensen** [colinbate/redux-form-submit-saga#15]
7.0.0 is out and should work just the same. I'm happy to PR it if you let me know how you'd prefer to set the range in the peerdependencies.

**Comment by elstob** [comment]
👍 @colinbate it seems like it's been almost half a year since you updated, please add some more contributors.

**Comment by colinbate** [comment]
This is now available in 1.2.0 and I suspect there will be a 1.2.1 out at some point with the update to `redux-saga` peer versions.
