### ISSUE TITLE
error doesn't work when using with immutable.js

### ISSUE THREAD

**Issue by josephktcheung** [colinbate/redux-form-submit-saga#2]
Hi,

First of all awesome library! Very convenient to use by not needing to write our own saga for redux-form.

One thing though, since I'm using immutable.js, `SubmissionError` doesn't show up in redux-form action because the library is not using the one exported from `redux-form/immutable` but from [`redux-form`](https://github.com/colinbate/redux-form-submit-saga/blob/master/index.js#L2). You may refer to this issue https://github.com/erikras/redux-form/issues/1713/

How to make this library support immutable.js? Thanks.

Best,
Joseph

**Comment by ghost** [comment]
I have the same problem !

**Comment by colinbate** [comment]
A fair point, I'll take a look at adding support for immutable.js as soon as I can.

**Comment by colinbate** [comment]
Release v1.1.0 should support immutable via imports on `redux-form-submit-saga/immutable`. Let me know if it isn't working for you, none of my test projects use it.
